// 50 realistic-looking reviews — ultra-realistic human avatars
export const reviewsData = [


  { name: "Aisha Khan", avatar: "https://randomuser.me/api/portraits/women/68.jpg", registered: "2023-11-08", earned: 324580, rating: 5, comment: "MetaXTrader has become my go-to platform. Deposits are smooth and trades execute fast. Support helped me once with a minor issue and were professional." },
  { name: "Carlos Mendez", avatar: "https://randomuser.me/api/portraits/men/45.jpg", registered: "2024-03-15", earned: 552840, rating: 5, comment: "Great UX and clean charts. I switched from another broker and the difference is night and day — withdrawals were processed quickly." },
  { name: "Sofia Rossi", avatar: "https://randomuser.me/api/portraits/women/22.jpg", registered: "2024-07-02", earned: 210000, rating: 5, comment: "Love the copy trading feature — simple to set up, and the signals performed as advertised during the trial period." },
  { name: "James Thompson", avatar: "https://randomuser.me/api/portraits/men/33.jpg", registered: "2023-10-21", earned: 184200, rating: 5, comment: "Solid platform. Mobile app works perfectly and the desktop view is great for deeper analysis. Fees are fair." },
  { name: "Lina Chen", avatar: "https://randomuser.me/api/portraits/women/15.jpg", registered: "2024-01-11", earned: 14320, rating: 5, comment: "I'm impressed with the educational resources. As a beginner I felt supported and confident making my first trades." },
  { name: "David O'Neil", avatar: "https://randomuser.me/api/portraits/men/56.jpg", registered: "2024-05-28", earned: 76320, rating: 5, comment: "Very reliable tick data and charts. Execution slippage has been minimal compared to other brokers I tried." },
  { name: "Priya Patel", avatar: "https://randomuser.me/api/portraits/women/31.jpg", registered: "2025-02-07", earned: 99750, rating: 5, comment: "Fantastic customer experience. The onboarding process was fast and the KYC took only a few minutes." },
  { name: "Mohamed El Sayed", avatar: "https://randomuser.me/api/portraits/men/18.jpg", registered: "2023-12-19", earned: 145000, rating: 5, comment: "I run multiple strategies and the platform handles them well. Helpful API docs for automating parts of my workflow." },
  { name: "Eva Novak", avatar: "https://randomuser.me/api/portraits/women/42.jpg", registered: "2024-10-03", earned: 8200, rating: 5, comment: "Beautiful UI and the charting tools have everything I need. Switching between timeframes is smooth and responsive." },
  { name: "Liam Murphy", avatar: "https://randomuser.me/api/portraits/men/67.jpg", registered: "2024-04-14", earned: 46200, rating: 5, comment: "Very happy with the liquidity on forex pairs. Spreads are competitive and fills are reliable." },
  { name: "Chloe Dubois", avatar: "https://randomuser.me/api/portraits/women/50.jpg", registered: "2024-06-11", earned: 112500, rating: 5, comment: "Customer support is responsive and helpful. I appreciate the detailed trade reports." },
  { name: "Ethan Brown", avatar: "https://randomuser.me/api/portraits/men/12.jpg", registered: "2024-02-22", earned: 89000, rating: 4, comment: "Good overall, though the app crashed once during heavy trading hours." },
  { name: "Mia Li", avatar: "https://randomuser.me/api/portraits/women/35.jpg", registered: "2023-11-29", earned: 54000, rating: 5, comment: "Love the automated alerts! They helped me catch a few high-profit trades." },
  { name: "Noah Smith", avatar: "https://randomuser.me/api/portraits/men/77.jpg", registered: "2024-08-17", earned: 23000, rating: 4, comment: "Interface is clean. Could improve charting indicators for advanced traders." },
  { name: "Zara Ahmed", avatar: "https://randomuser.me/api/portraits/women/11.jpg", registered: "2024-09-12", earned: 16700, rating: 5, comment: "Quick withdrawals and clear reports. I feel confident using the platform." },
  { name: "Oliver Johnson", avatar: "https://randomuser.me/api/portraits/men/88.jpg", registered: "2024-03-01", earned: 12450, rating: 4, comment: "Good trading platform, minor latency during high volatility periods." },
  { name: "Layla Torres", avatar: "https://randomuser.me/api/portraits/women/9.jpg", registered: "2024-01-30", earned: 21000, rating: 5, comment: "Copy trading is amazing, beginner-friendly and consistent signals." },


  { name: "Amelia Green", avatar: "https://randomuser.me/api/portraits/women/60.jpg", registered: "2024-07-25", earned: 9700, rating: 5, comment: "Educational materials helped me a lot to improve my trading knowledge." },
  { name: "Lukas Weber", avatar: "https://randomuser.me/api/portraits/men/44.jpg", registered: "2024-06-08", earned: 102000, rating: 5, comment: "Fast deposits and withdrawals. Charts are easy to read and accurate." },
  { name: "Sophia Bell", avatar: "https://randomuser.me/api/portraits/women/38.jpg", registered: "2024-05-20", earned: 155000, rating: 5, comment: "Really enjoy using the platform. Smooth experience on both desktop and mobile." },
  { name: "Mateo Gonzalez", avatar: "https://randomuser.me/api/portraits/men/21.jpg", registered: "2024-04-18", earned: 76000, rating: 4, comment: "Good execution speed, some minor UI quirks though." },
  { name: "Hana Suzuki", avatar: "https://randomuser.me/api/portraits/women/27.jpg", registered: "2024-03-11", earned: 29000, rating: 5, comment: "I love the interface — easy to navigate and very responsive." },
  { name: "Jacob Lee", avatar: "https://randomuser.me/api/portraits/men/66.jpg", registered: "2023-10-19", earned: 450000, rating: 5, comment: "Good liquidity and low spreads. I’ve recommended to colleagues." },
  { name: "Isabella Martinez", avatar: "https://randomuser.me/api/portraits/women/29.jpg", registered: "2024-01-05", earned: 67000, rating: 5, comment: "Customer support is excellent. They quickly solved my issue." },
  { name: "Ryan Walker", avatar: "https://randomuser.me/api/portraits/men/53.jpg", registered: "2024-02-15", earned: 38400, rating: 4, comment: "Smooth deposits. Mobile interface is a bit cramped on small screens." },
  { name: "Ella Davis", avatar: "https://randomuser.me/api/portraits/women/41.jpg", registered: "2024-08-02", earned: 23000, rating: 5, comment: "Really enjoy the signal notifications — they are accurate most of the time." },
  { name: "Mason Brown", avatar: "https://randomuser.me/api/portraits/men/38.jpg", registered: "2024-09-22", earned: 9100, rating: 5, comment: "Reliable platform. Trading bots work as expected." },
  { name: "Grace Kim", avatar: "https://randomuser.me/api/portraits/women/16.jpg", registered: "2024-10-12", earned: 18500, rating: 5, comment: "Charts are excellent. Easy to analyze trends and execute trades." },
  { name: "Noah Patel", avatar: "https://randomuser.me/api/portraits/men/34.jpg", registered: "2024-06-30", earned: 47000, rating: 5, comment: "Good for both beginners and pros. I’ve learned a lot using the platform." },
  { name: "Chloe Smith", avatar: "https://randomuser.me/api/portraits/women/47.jpg", registered: "2024-05-09", earned: 12300, rating: 4, comment: "User interface is nice. Occasionally slow during heavy traffic." },
  { name: "Liam Brown", avatar: "https://randomuser.me/api/portraits/men/7.jpg", registered: "2024-01-28", earned: 89000, rating: 5, comment: "Excellent execution and responsive support team." },
  { name: "Zoe Wang", avatar: "https://randomuser.me/api/portraits/women/3.jpg", registered: "2024-03-17", earned: 67000, rating: 5, comment: "Very happy with performance. UI is clear and simple." },
  { name: "Ethan White", avatar: "https://randomuser.me/api/portraits/men/2.jpg", registered: "2024-02-20", earned: 17000, rating: 4, comment: "Good experience overall. Some minor bugs with chart overlays." },
  { name: "Hannah Lee", avatar: "https://randomuser.me/api/portraits/women/5.jpg", registered: "2024-04-01", earned: 12000, rating: 5, comment: "Customer support is fast and helpful. Love the daily insights." },
  { name: "Oliver Brown", avatar: "https://randomuser.me/api/portraits/men/6.jpg", registered: "2024-07-11", earned: 9000, rating: 5, comment: "Very stable and reliable. Mobile app works great." },
  { name: "Sophia Green", avatar: "https://randomuser.me/api/portraits/women/21.jpg", registered: "2024-05-18", earned: 98000, rating: 5, comment: "Charts are very detailed. I like the dark theme option." },
  { name: "Keith Bradley", avatar: "https://randomuser.me/api/portraits/men/99.jpg", registered: "2024-04-20", earned: 0, rating: 1, comment: "i gave you 5 star before, but i made a mistake putting in my signal code and was suspended , it has been a longtime since i made a report and still nothing has been done, i will change my rating back to 5 star if you can please assist me with this" },

  // 10 more realistic reviews (fill up to 50)
  { name: "Lucas Wright", avatar: "https://randomuser.me/api/portraits/men/50.jpg", registered: "2024-03-23", earned: 40000, rating: 5, comment: "Platform is very fast, and I like the trading bots integration." },
  { name: "Emma Hall", avatar: "https://randomuser.me/api/portraits/women/18.jpg", registered: "2024-02-19", earned: 15000, rating: 5, comment: "Mobile app is intuitive, and the signals are accurate." },
  { name: "Logan Scott", avatar: "https://randomuser.me/api/portraits/men/26.jpg", registered: "2024-04-14", earned: 88000, rating: 5, comment: "I like the risk management tools, very practical." },
  { name: "Ava Adams", avatar: "https://randomuser.me/api/portraits/women/2.jpg", registered: "2024-01-21", earned: 53000, rating: 5, comment: "Good platform, beginner-friendly and fast support." },
  { name: "Eli Carter", avatar: "https://randomuser.me/api/portraits/men/9.jpg", registered: "2024-03-30", earned: 72000, rating: 5, comment: "I appreciate the low spreads and fast execution." },
  { name: "Lily Evans", avatar: "https://randomuser.me/api/portraits/women/6.jpg", registered: "2024-06-02", earned: 47000, rating: 5, comment: "Excellent charts and easy to customize layouts." },
  { name: "Sebastian Lewis", avatar: "https://randomuser.me/api/portraits/men/33.jpg", registered: "2024-04-05", earned: 91000, rating: 5, comment: "Support team is fast and helpful, very professional." },
  { name: "Madison Hall", avatar: "https://randomuser.me/api/portraits/women/7.jpg", registered: "2024-05-27", earned: 65000, rating: 5, comment: "Love the automated trading features — very reliable." },
  { name: "Henry King", avatar: "https://randomuser.me/api/portraits/men/40.jpg", registered: "2024-07-13", earned: 87000, rating: 5, comment: "Platform runs smoothly. API documentation is solid." },
  { name: "Chloe Wilson", avatar: "https://randomuser.me/api/portraits/women/14.jpg", registered: "2024-06-20", earned: 50000, rating: 5, comment: "Charts are very accurate, love the dark mode for trading at night." },

    // +100 additional realistic reviews (append to reviewsData)
  { name: "Natalie Lopez", avatar: "https://randomuser.me/api/portraits/women/0.jpg", registered: "2024-09-23", earned: 227500, rating: 4, comment: "VIP system makes sense and rewards active trading without feeling like a gimmick." },
  { name: "Blake Foster", avatar: "https://randomuser.me/api/portraits/men/0.jpg", registered: "2024-02-15", earned: 223000, rating: 5, comment: "Copy trading and signals are on point — I like how realistic the results have been." },
  { name: "Bianca Martin", avatar: "https://randomuser.me/api/portraits/women/1.jpg", registered: "2024-04-11", earned: 184500, rating: 4, comment: "Spreads are fair and execution is reliable even during high volatility." },
  { name: "Caleb Costa", avatar: "https://randomuser.me/api/portraits/men/1.jpg", registered: "2024-08-19", earned: 205000, rating: 4, comment: "Deposits and withdrawals have been smooth so far, no hidden surprises." },
  { name: "Riley Santos", avatar: "https://randomuser.me/api/portraits/women/4.jpg", registered: "2025-02-01", earned: 265500, rating: 5, comment: "Interface feels premium and loads quickly on my laptop and phone." },
  { name: "Derek Silva", avatar: "https://randomuser.me/api/portraits/men/3.jpg", registered: "2024-10-16", earned: 126500, rating: 4, comment: "The platform reports and PnL breakdowns are very clear and easy to export." },
  { name: "Jasmine Nguyen", avatar: "https://randomuser.me/api/portraits/women/8.jpg", registered: "2024-03-19", earned: 123000, rating: 5, comment: "Risk management tools help me control my exposure on each trade." },
  { name: "Elliot Petrov", avatar: "https://randomuser.me/api/portraits/men/4.jpg", registered: "2024-07-30", earned: 252000, rating: 5, comment: "Support actually replies with useful answers instead of canned responses." },
  { name: "Tara Hansen", avatar: "https://randomuser.me/api/portraits/women/10.jpg", registered: "2024-01-20", earned: 198500, rating: 4, comment: "Onboarding and KYC were straightforward, I was trading the same day." },
  { name: "Felix Meyer", avatar: "https://randomuser.me/api/portraits/men/5.jpg", registered: "2023-11-19", earned: 151500, rating: 5, comment: "Mobile layout is clean, I can monitor my open trades without stress." },
  { name: "Naomi Schmidt", avatar: "https://randomuser.me/api/portraits/women/12.jpg", registered: "2024-02-01", earned: 232000, rating: 5, comment: "The learning curve was gentle thanks to the in-app tutorials." },
  { name: "Gavin Novak", avatar: "https://randomuser.me/api/portraits/men/8.jpg", registered: "2024-07-11", earned: 260000, rating: 5, comment: "Copy trading has been a nice way to diversify without watching charts all day." },
  { name: "Sara Khan", avatar: "https://randomuser.me/api/portraits/women/13.jpg", registered: "2024-05-24", earned: 118500, rating: 4, comment: "VIP tiers push me to stay disciplined and stick to my trading rules." },
  { name: "Hugo Ali", avatar: "https://randomuser.me/api/portraits/men/10.jpg", registered: "2024-07-06", earned: 88500, rating: 4, comment: "I appreciate how transparent the fees and commissions are." },
  { name: "Helena Dias", avatar: "https://randomuser.me/api/portraits/women/17.jpg", registered: "2024-10-21", earned: 162500, rating: 5, comment: "Charts are responsive and the drawing tools feel smooth to use." },
  { name: "Isaac Santos", avatar: "https://randomuser.me/api/portraits/men/11.jpg", registered: "2024-08-07", earned: 243000, rating: 5, comment: "The dashboard makes it easy to see overall performance at a glance." },
  { name: "Vivian Rossi", avatar: "https://randomuser.me/api/portraits/women/19.jpg", registered: "2024-08-03", earned: 194000, rating: 4, comment: "Email alerts and notifications are timed well, not spammy at all." },
  { name: "Jonas Ricci", avatar: "https://randomuser.me/api/portraits/men/13.jpg", registered: "2024-07-09", earned: 232500, rating: 5, comment: "I like that the platform feels modern but not overloaded with useless widgets." },
  { name: "Brooke Foster", avatar: "https://randomuser.me/api/portraits/women/20.jpg", registered: "2024-03-25", earned: 111000, rating: 4, comment: "Trade history and exportable statements are great for my accounting." },
  { name: "Kyle Parker", avatar: "https://randomuser.me/api/portraits/men/14.jpg", registered: "2023-12-16", earned: 219500, rating: 5, comment: "Everything feels stable — no random freezes when the market moves fast." },
  { name: "Ivy Murphy", avatar: "https://randomuser.me/api/portraits/women/23.jpg", registered: "2024-09-11", earned: 265000, rating: 5, comment: "Copy trading and signals are on point — I like how realistic the results have been." },
  { name: "Logan Collins", avatar: "https://randomuser.me/api/portraits/men/15.jpg", registered: "2024-09-08", earned: 184500, rating: 4, comment: "Spreads are fair and execution is reliable even during high volatility." },
  { name: "Alina Bennett", avatar: "https://randomuser.me/api/portraits/women/24.jpg", registered: "2024-01-03", earned: 123500, rating: 5, comment: "Deposits and withdrawals have been smooth so far, no hidden surprises." },
  { name: "Marcus Hughes", avatar: "https://randomuser.me/api/portraits/men/16.jpg", registered: "2024-10-29", earned: 217000, rating: 4, comment: "Interface feels premium and loads quickly on my laptop and phone." },
  { name: "Nora Wong", avatar: "https://randomuser.me/api/portraits/women/25.jpg", registered: "2024-04-16", earned: 290500, rating: 5, comment: "The platform reports and PnL breakdowns are very clear and easy to export." },
  { name: "Noel Lin", avatar: "https://randomuser.me/api/portraits/men/17.jpg", registered: "2024-02-21", earned: 193500, rating: 4, comment: "Risk management tools help me control my exposure on each trade." },
  { name: "Camila Choi", avatar: "https://randomuser.me/api/portraits/women/26.jpg", registered: "2024-01-02", earned: 215500, rating: 5, comment: "Support actually replies with useful answers instead of canned responses." },
  { name: "Parker Dubois", avatar: "https://randomuser.me/api/portraits/men/19.jpg", registered: "2024-03-06", earned: 141500, rating: 4, comment: "Onboarding and KYC were straightforward, I was trading the same day." },
  { name: "Diana Martin", avatar: "https://randomuser.me/api/portraits/women/28.jpg", registered: "2024-09-22", earned: 150500, rating: 4, comment: "Mobile layout is clean, I can monitor my open trades without stress." },
  { name: "Reid Clark", avatar: "https://randomuser.me/api/portraits/men/20.jpg", registered: "2024-05-26", earned: 230500, rating: 5, comment: "The learning curve was gentle thanks to the in-app tutorials." },
  { name: "Elena Cooper", avatar: "https://randomuser.me/api/portraits/women/30.jpg", registered: "2024-07-20", earned: 213000, rating: 5, comment: "Copy trading has been a nice way to diversify without watching charts all day." },
  { name: "Samir Turner", avatar: "https://randomuser.me/api/portraits/men/22.jpg", registered: "2024-01-06", earned: 255500, rating: 5, comment: "VIP tiers push me to stay disciplined and stick to my trading rules." },
  { name: "Katherine Edwards", avatar: "https://randomuser.me/api/portraits/women/32.jpg", registered: "2024-08-24", earned: 157500, rating: 4, comment: "I appreciate how transparent the fees and commissions are." },
  { name: "Ulrich Price", avatar: "https://randomuser.me/api/portraits/men/24.jpg", registered: "2024-06-18", earned: 201500, rating: 4, comment: "Charts are responsive and the drawing tools feel smooth to use." },
  { name: "Maya King", avatar: "https://randomuser.me/api/portraits/women/33.jpg", registered: "2024-07-28", earned: 135500, rating: 4, comment: "The dashboard makes it easy to see overall performance at a glance." },
  { name: "Victor Knight", avatar: "https://randomuser.me/api/portraits/men/25.jpg", registered: "2024-03-19", earned: 160000, rating: 5, comment: "Email alerts and notifications are timed well, not spammy at all." },
  { name: "Paige Russell", avatar: "https://randomuser.me/api/portraits/women/34.jpg", registered: "2024-10-09", earned: 273500, rating: 5, comment: "I like that the platform feels modern but not overloaded with useless widgets." },
  
  { name: "Harper Shaw", avatar: "https://randomuser.me/api/portraits/women/36.jpg", registered: "2024-03-31", earned: 177500, rating: 5, comment: "Everything feels stable — no random freezes when the market moves fast." },
  { name: "Xander Reyes", avatar: "https://randomuser.me/api/portraits/men/28.jpg", registered: "2024-09-06", earned: 116500, rating: 4, comment: "Copy trading and signals are on point — I like how realistic the results have been." },
  { name: "Jade Flores", avatar: "https://randomuser.me/api/portraits/women/37.jpg", registered: "2024-06-13", earned: 291500, rating: 5, comment: "Spreads are fair and execution is reliable even during high volatility." },
  { name: "Yuri Kaur", avatar: "https://randomuser.me/api/portraits/men/29.jpg", registered: "2024-03-29", earned: 98000, rating: 4, comment: "Deposits and withdrawals have been smooth so far, no hidden surprises." },
  { name: "Ruby Singh", avatar: "https://randomuser.me/api/portraits/women/39.jpg", registered: "2024-09-17", earned: 138500, rating: 4, comment: "Interface feels premium and loads quickly on my laptop and phone." },
  { name: "Zane Iqbal", avatar: "https://randomuser.me/api/portraits/men/30.jpg", registered: "2024-02-23", earned: 259000, rating: 5, comment: "The platform reports and PnL breakdowns are very clear and easy to export." },
  { name: "Sienna Yamada", avatar: "https://randomuser.me/api/portraits/women/40.jpg", registered: "2024-02-06", earned: 147500, rating: 4, comment: "Risk management tools help me control my exposure on each trade." },
  { name: "Arthur Tanaka", avatar: "https://randomuser.me/api/portraits/men/31.jpg", registered: "2024-03-22", earned: 150000, rating: 4, comment: "Support actually replies with useful answers instead of canned responses." },
  { name: "Tessa Kato", avatar: "https://randomuser.me/api/portraits/women/43.jpg", registered: "2024-04-09", earned: 264000, rating: 5, comment: "Onboarding and KYC were straightforward, I was trading the same day." },
  { name: "Ben Franco", avatar: "https://randomuser.me/api/portraits/men/32.jpg", registered: "2024-06-15", earned: 196000, rating: 5, comment: "Mobile layout is clean, I can monitor my open trades without stress." },
  { name: "Lola Torres", avatar: "https://randomuser.me/api/portraits/women/44.jpg", registered: "2024-06-08", earned: 159500, rating: 4, comment: "The learning curve was gentle thanks to the in-app tutorials." },
  { name: "Colin Lopez", avatar: "https://randomuser.me/api/portraits/men/35.jpg", registered: "2024-07-02", earned: 122000, rating: 4, comment: "Copy trading has been a nice way to diversify without watching charts all day." },
  { name: "Francesca Reed", avatar: "https://randomuser.me/api/portraits/women/45.jpg", registered: "2024-02-17", earned: 108500, rating: 5, comment: "VIP tiers push me to stay disciplined and stick to my trading rules." },
  { name: "Damian Morgan", avatar: "https://randomuser.me/api/portraits/men/36.jpg", registered: "2023-10-10", earned: 121000, rating: 4, comment: "I appreciate how transparent the fees and commissions are." },
  { name: "Mila Lopez", avatar: "https://randomuser.me/api/portraits/women/46.jpg", registered: "2024-10-15", earned: 243500, rating: 5, comment: "Charts are responsive and the drawing tools feel smooth to use." },
  { name: "Emil Garcia", avatar: "https://randomuser.me/api/portraits/men/37.jpg", registered: "2024-08-28", earned: 214500, rating: 5, comment: "The dashboard makes it easy to see overall performance at a glance." },
  { name: "Ada Costa", avatar: "https://randomuser.me/api/portraits/women/48.jpg", registered: "2024-09-10", earned: 103500, rating: 4, comment: "Email alerts and notifications are timed well, not spammy at all." },
  { name: "Fraser Silva", avatar: "https://randomuser.me/api/portraits/men/39.jpg", registered: "2024-04-04", earned: 297500, rating: 5, comment: "I like that the platform feels modern but not overloaded with useless widgets." },
  { name: "Amira Nguyen", avatar: "https://randomuser.me/api/portraits/women/49.jpg", registered: "2024-01-18", earned: 146000, rating: 4, comment: "Trade history and exportable statements are great for my accounting." },
  { name: "Grant Petrov", avatar: "https://randomuser.me/api/portraits/men/41.jpg", registered: "2024-10-06", earned: 253000, rating: 5, comment: "Everything feels stable — no random freezes when the market moves fast." },
  { name: "Clara Hansen", avatar: "https://randomuser.me/api/portraits/women/51.jpg", registered: "2024-08-11", earned: 174500, rating: 5, comment: "Copy trading and signals are on point — I like how realistic the results have been." },
  { name: "Hayden Meyer", avatar: "https://randomuser.me/api/portraits/men/42.jpg", registered: "2024-09-12", earned: 177500, rating: 4, comment: "Spreads are fair and execution is reliable even during high volatility." },
  { name: "Nadia Schmidt", avatar: "https://randomuser.me/api/portraits/women/52.jpg", registered: "2024-02-08", earned: 160500, rating: 4, comment: "Deposits and withdrawals have been smooth so far, no hidden surprises." },
  { name: "Ian Novak", avatar: "https://randomuser.me/api/portraits/men/43.jpg", registered: "2024-03-05", earned: 145500, rating: 4, comment: "Interface feels premium and loads quickly on my laptop and phone." },
  { name: "Valerie Khan", avatar: "https://randomuser.me/api/portraits/women/53.jpg", registered: "2024-10-01", earned: 196000, rating: 5, comment: "The platform reports and PnL breakdowns are very clear and easy to export." },
  { name: "Joel Ali", avatar: "https://randomuser.me/api/portraits/men/46.jpg", registered: "2024-08-14", earned: 255500, rating: 5, comment: "Risk management tools help me control my exposure on each trade." },
  { name: "Iris Dias", avatar: "https://randomuser.me/api/portraits/women/54.jpg", registered: "2024-04-07", earned: 273500, rating: 5, comment: "Support actually replies with useful answers instead of canned responses." },
  { name: "Kieran Santos", avatar: "https://randomuser.me/api/portraits/men/47.jpg", registered: "2024-08-20", earned: 180000, rating: 4, comment: "Onboarding and KYC were straightforward, I was trading the same day." },
  { name: "June Rossi", avatar: "https://randomuser.me/api/portraits/women/55.jpg", registered: "2024-01-29", earned: 148000, rating: 4, comment: "Mobile layout is clean, I can monitor my open trades without stress." },
  { name: "Lukas Ricci", avatar: "https://randomuser.me/api/portraits/men/48.jpg", registered: "2024-08-01", earned: 266000, rating: 5, comment: "The learning curve was gentle thanks to the in-app tutorials." },
  { name: "Keira Foster", avatar: "https://randomuser.me/api/portraits/women/56.jpg", registered: "2023-10-20", earned: 183000, rating: 4, comment: "Copy trading has been a nice way to diversify without watching charts all day." },
  { name: "Mason Parker", avatar: "https://randomuser.me/api/portraits/men/51.jpg", registered: "2024-07-14", earned: 243500, rating: 5, comment: "VIP tiers push me to stay disciplined and stick to my trading rules." },
  { name: "Lena Murphy", avatar: "https://randomuser.me/api/portraits/women/57.jpg", registered: "2024-07-05", earned: 130000, rating: 4, comment: "I appreciate how transparent the fees and commissions are." },
  { name: "Rafael Collins", avatar: "https://randomuser.me/api/portraits/men/52.jpg", registered: "2024-10-19", earned: 161500, rating: 4, comment: "Charts are responsive and the drawing tools feel smooth to use." },
  { name: "Marina Davis", avatar: "https://randomuser.me/api/portraits/women/58.jpg", registered: "2024-04-26", earned: 110000, rating: 4, comment: "The dashboard makes it easy to see overall performance at a glance." },
  { name: "Simon Bennett", avatar: "https://randomuser.me/api/portraits/men/54.jpg", registered: "2024-06-22", earned: 275500, rating: 5, comment: "Email alerts and notifications are timed well, not spammy at all." },
  { name: "Nina Hughes", avatar: "https://randomuser.me/api/portraits/women/59.jpg", registered: "2024-01-09", earned: 154500, rating: 4, comment: "I like that the platform feels modern but not overloaded with useless widgets." },
  { name: "Tyler Wong", avatar: "https://randomuser.me/api/portraits/men/55.jpg", registered: "2024-06-19", earned: 118000, rating: 4, comment: "Trade history and exportable statements are great for my accounting." },
  { name: "Olivia Lin", avatar: "https://randomuser.me/api/portraits/women/61.jpg", registered: "2024-06-27", earned: 268000, rating: 5, comment: "Everything feels stable — no random freezes when the market moves fast." },
  { name: "Viktor Choi", avatar: "https://randomuser.me/api/portraits/men/57.jpg", registered: "2024-05-14", earned: 178000, rating: 4, comment: "Copy trading and signals are on point — I like how realistic the results have been." },
  { name: "Poppy Dubois", avatar: "https://randomuser.me/api/portraits/women/62.jpg", registered: "2024-03-21", earned: 131000, rating: 4, comment: "Spreads are fair and execution is reliable even during high volatility." },
  { name: "Warren Martin", avatar: "https://randomuser.me/api/portraits/men/58.jpg", registered: "2024-03-09", earned: 194000, rating: 4, comment: "Deposits and withdrawals have been smooth so far, no hidden surprises." },
  { name: "Quinn Clark", avatar: "https://randomuser.me/api/portraits/women/63.jpg", registered: "2024-02-10", earned: 169000, rating: 5, comment: "Interface feels premium and loads quickly on my laptop and phone." },
  { name: "Xavi Cooper", avatar: "https://randomuser.me/api/portraits/men/59.jpg", registered: "2024-01-24", earned: 167000, rating: 4, comment: "The platform reports and PnL breakdowns are very clear and easy to export." },
  { name: "Renee Turner", avatar: "https://randomuser.me/api/portraits/women/64.jpg", registered: "2024-03-02", earned: 102500, rating: 4, comment: "Risk management tools help me control my exposure on each trade." },
  { name: "Yousef Edwards", avatar: "https://randomuser.me/api/portraits/men/61.jpg", registered: "2024-07-01", earned: 281000, rating: 5, comment: "Support actually replies with useful answers instead of canned responses." },
  { name: "Sasha Price", avatar: "https://randomuser.me/api/portraits/women/65.jpg", registered: "2024-04-03", earned: 225500, rating: 5, comment: "Onboarding and KYC were straightforward, I was trading the same day." },
  { name: "Zack King", avatar: "https://randomuser.me/api/portraits/men/62.jpg", registered: "2024-09-28", earned: 137000, rating: 4, comment: "Mobile layout is clean, I can monitor my open trades without stress." },
  { name: "Talia Knight", avatar: "https://randomuser.me/api/portraits/women/66.jpg", registered: "2024-02-13", earned: 180500, rating: 4, comment: "The learning curve was gentle thanks to the in-app tutorials." },
  { name: "Adrian Russell", avatar: "https://randomuser.me/api/portraits/men/63.jpg", registered: "2024-04-15", earned: 163000, rating: 4, comment: "Copy trading has been a nice way to diversify without watching charts all day." },
  { name: "Uma Fisher", avatar: "https://randomuser.me/api/portraits/women/67.jpg", registered: "2024-07-23", earned: 294000, rating: 5, comment: "VIP tiers push me to stay disciplined and stick to my trading rules." },
  { name: "Blake Shaw", avatar: "https://randomuser.me/api/portraits/men/64.jpg", registered: "2024-06-05", earned: 152500, rating: 4, comment: "I appreciate how transparent the fees and commissions are." },
  { name: "Veronica Reyes", avatar: "https://randomuser.me/api/portraits/women/69.jpg", registered: "2023-11-13", earned: 190000, rating: 5, comment: "Charts are responsive and the drawing tools feel smooth to use." },
  { name: "Colin Flores", avatar: "https://randomuser.me/api/portraits/men/65.jpg", registered: "2024-09-03", earned: 120500, rating: 4, comment: "The dashboard makes it easy to see overall performance at a glance." },
  { name: "Willow Kaur", avatar: "https://randomuser.me/api/portraits/women/70.jpg", registered: "2024-05-05", earned: 108000, rating: 4, comment: "Email alerts and notifications are timed well, not spammy at all." },
  { name: "Damian Singh", avatar: "https://randomuser.me/api/portraits/men/69.jpg", registered: "2024-04-24", earned: 282500, rating: 5, comment: "I like that the platform feels modern but not overloaded with useless widgets." },
  { name: "Xenia Iqbal", avatar: "https://randomuser.me/api/portraits/women/71.jpg", registered: "2024-08-22", earned: 114500, rating: 4, comment: "Trade history and exportable statements are great for my accounting." },
  { name: "Emil Yamada", avatar: "https://randomuser.me/api/portraits/men/70.jpg", registered: "2024-05-07", earned: 209000, rating: 5, comment: "Everything feels stable — no random freezes when the market moves fast." },
  { name: "Yasmin Tanaka", avatar: "https://randomuser.me/api/portraits/women/72.jpg", registered: "2024-06-10", earned: 173500, rating: 4, comment: "Copy trading and signals are on point — I like how realistic the results have been." },
  { name: "Fraser Kato", avatar: "https://randomuser.me/api/portraits/men/71.jpg", registered: "2023-12-08", earned: 148500, rating: 4, comment: "Spreads are fair and execution is reliable even during high volatility." },
  { name: "Zoe Franco", avatar: "https://randomuser.me/api/portraits/women/73.jpg", registered: "2024-01-15", earned: 189500, rating: 5, comment: "Deposits and withdrawals have been smooth so far, no hidden surprises." },
  { name: "Keith Bradley", avatar: "https://randomuser.me/api/portraits/men/72.jpg", registered: "2024-09-20", earned: 238500, rating: 5, comment: "Interface feels premium and loads quickly on my laptop and phone." },
  { name: "Aisha Lopez", avatar: "https://randomuser.me/api/portraits/women/74.jpg", registered: "2024-02-04", earned: 107000, rating: 4, comment: "The platform reports and PnL breakdowns are very clear and easy to export." },
  { name: "Hayden Reed", avatar: "https://randomuser.me/api/portraits/men/73.jpg", registered: "2024-08-05", earned: 272000, rating: 5, comment: "Risk management tools help me control my exposure on each trade." },
  { name: "Bianca Morgan", avatar: "https://randomuser.me/api/portraits/women/75.jpg", registered: "2024-09-26", earned: 215000, rating: 5, comment: "Support actually replies with useful answers instead of canned responses." },
  { name: "Ian Lopez", avatar: "https://randomuser.me/api/portraits/men/74.jpg", registered: "2024-04-30", earned: 195500, rating: 4, comment: "Onboarding and KYC were straightforward, I was trading the same day." },
  { name: "Riley Garcia", avatar: "https://randomuser.me/api/portraits/women/76.jpg", registered: "2024-03-16", earned: 128000, rating: 4, comment: "Mobile layout is clean, I can monitor my open trades without stress." },
  { name: "Joel Costa", avatar: "https://randomuser.me/api/portraits/men/75.jpg", registered: "2024-03-27", earned: 203500, rating: 4, comment: "The learning curve was gentle thanks to the in-app tutorials." },
  { name: "Jasmine Silva", avatar: "https://randomuser.me/api/portraits/women/77.jpg", registered: "2024-07-16", earned: 220500, rating: 5, comment: "Copy trading has been a nice way to diversify without watching charts all day." },
  { name: "Kieran Nguyen", avatar: "https://randomuser.me/api/portraits/men/76.jpg", registered: "2024-02-26", earned: 158000, rating: 4, comment: "VIP tiers push me to stay disciplined and stick to my trading rules." },
  { name: "Naomi Petrov", avatar: "https://randomuser.me/api/portraits/women/78.jpg", registered: "2024-09-02", earned: 249000, rating: 5, comment: "I appreciate how transparent the fees and commissions are." },
  { name: "Lukas Hansen", avatar: "https://randomuser.me/api/portraits/men/78.jpg", registered: "2024-05-23", earned: 145000, rating: 4, comment: "Charts are responsive and the drawing tools feel smooth to use." },
  { name: "Helena Meyer", avatar: "https://randomuser.me/api/portraits/women/79.jpg", registered: "2024-01-26", earned: 193000, rating: 5, comment: "The dashboard makes it easy to see overall performance at a glance." },
  { name: "Mason Schmidt", avatar: "https://randomuser.me/api/portraits/men/79.jpg", registered: "2024-06-01", earned: 139000, rating: 4, comment: "Email alerts and notifications are timed well, not spammy at all." },
  { name: "Lina Novak", avatar: "https://randomuser.me/api/portraits/women/80.jpg", registered: "2024-10-05", earned: 260500, rating: 5, comment: "I like that the platform feels modern but not overloaded with useless widgets." },
  { name: "Nolan Khan", avatar: "https://randomuser.me/api/portraits/men/80.jpg", registered: "2024-03-03", earned: 120000, rating: 4, comment: "Trade history and exportable statements are great for my accounting." },
  { name: "Sofia Ali", avatar: "https://randomuser.me/api/portraits/women/81.jpg", registered: "2024-02-12", earned: 148500, rating: 4, comment: "Everything feels stable — no random freezes when the market moves fast." },
  { name: "Oscar Dias", avatar: "https://randomuser.me/api/portraits/men/81.jpg", registered: "2023-11-28", earned: 297000, rating: 5, comment: "Copy trading and signals are on point — I like how realistic the results have been." },
  { name: "Grace Santos", avatar: "https://randomuser.me/api/portraits/women/82.jpg", registered: "2024-07-19", earned: 161000, rating: 4, comment: "Spreads are fair and execution is reliable even during high volatility." },
  { name: "Philip Rossi", avatar: "https://randomuser.me/api/portraits/men/82.jpg", registered: "2024-09-25", earned: 171500, rating: 4, comment: "Deposits and withdrawals have been smooth so far, no hidden surprises." },
  { name: "Hannah Ricci", avatar: "https://randomuser.me/api/portraits/women/83.jpg", registered: "2024-03-01", earned: 111500, rating: 4, comment: "Interface feels premium and loads quickly on my laptop and phone." },
  { name: "Rafael Foster", avatar: "https://randomuser.me/api/portraits/men/83.jpg", registered: "2024-01-14", earned: 104000, rating: 4, comment: "The platform reports and PnL breakdowns are very clear and easy to export." },
  { name: "Ella Parker", avatar: "https://randomuser.me/api/portraits/women/84.jpg", registered: "2024-02-25", earned: 185500, rating: 5, comment: "Risk management tools help me control my exposure on each trade." },
  { name: "Simon Murphy", avatar: "https://randomuser.me/api/portraits/men/84.jpg", registered: "2024-08-09", earned: 231000, rating: 5, comment: "Support actually replies with useful answers instead of canned responses." },
  { name: "Mila Collins", avatar: "https://randomuser.me/api/portraits/women/85.jpg", registered: "2024-05-03", earned: 193500, rating: 5, comment: "Onboarding and KYC were straightforward, I was trading the same day." },
  { name: "Tyler Bennett", avatar: "https://randomuser.me/api/portraits/men/85.jpg", registered: "2024-04-21", earned: 214000, rating: 4, comment: "Mobile layout is clean, I can monitor my open trades without stress." },
  { name: "Ada Hughes", avatar: "https://randomuser.me/api/portraits/women/86.jpg", registered: "2023-12-27", earned: 132500, rating: 4, comment: "The learning curve was gentle thanks to the in-app tutorials." },
  { name: "Victor Wong", avatar: "https://randomuser.me/api/portraits/men/86.jpg", registered: "2024-09-01", earned: 290000, rating: 5, comment: "Copy trading has been a nice way to diversify without watching charts all day." },
  { name: "Nadia Lin", avatar: "https://randomuser.me/api/portraits/women/87.jpg", registered: "2024-06-16", earned: 115500, rating: 4, comment: "VIP tiers push me to stay disciplined and stick to my trading rules." },
  { name: "Wyatt Choi", avatar: "https://randomuser.me/api/portraits/men/87.jpg", registered: "2024-05-28", earned: 186500, rating: 4, comment: "I appreciate how transparent the fees and commissions are." },
  { name: "Valerie Dubois", avatar: "https://randomuser.me/api/portraits/women/88.jpg", registered: "2024-07-31", earned: 178500, rating: 5, comment: "Charts are responsive and the drawing tools feel smooth to use." },
  { name: "Xander Martin", avatar: "https://randomuser.me/api/portraits/men/89.jpg", registered: "2023-11-03", earned: 118500, rating: 4, comment: "The dashboard makes it easy to see overall performance at a glance." },
  { name: "Iris Clark", avatar: "https://randomuser.me/api/portraits/women/89.jpg", registered: "2024-01-31", earned: 124500, rating: 4, comment: "Email alerts and notifications are timed well, not spammy at all." },
  { name: "Yuri Cooper", avatar: "https://randomuser.me/api/portraits/men/90.jpg", registered: "2024-06-12", earned: 222000, rating: 5, comment: "I like that the platform feels modern but not overloaded with useless widgets." },
  { name: "June Turner", avatar: "https://randomuser.me/api/portraits/women/90.jpg", registered: "2024-10-18", earned: 203000, rating: 5, comment: "Trade history and exportable statements are great for my accounting." },
  { name: "Zane Edwards", avatar: "https://randomuser.me/api/portraits/men/91.jpg", registered: "2024-03-13", earned: 174000, rating: 4, comment: "Everything feels stable — no random freezes when the market moves fast." },
  { name: "Keira Price", avatar: "https://randomuser.me/api/portraits/women/91.jpg", registered: "2024-05-01", earned: 141000, rating: 4, comment: "Copy trading and signals are on point — I like how realistic the results have been." },
  { name: "Arthur King", avatar: "https://randomuser.me/api/portraits/men/92.jpg", registered: "2024-02-18", earned: 247500, rating: 5, comment: "Spreads are fair and execution is reliable even during high volatility." },
  { name: "Lena Knight", avatar: "https://randomuser.me/api/portraits/women/92.jpg", registered: "2024-03-08", earned: 157000, rating: 4, comment: "Deposits and withdrawals have been smooth so far, no hidden surprises." },
  { name: "Ben Russell", avatar: "https://randomuser.me/api/portraits/men/93.jpg", registered: "2024-09-15", earned: 181500, rating: 4, comment: "Interface feels premium and loads quickly on my laptop and phone." },
  { name: "Marina Fisher", avatar: "https://randomuser.me/api/portraits/women/93.jpg", registered: "2024-04-12", earned: 248500, rating: 5, comment: "The platform reports and PnL breakdowns are very clear and easy to export." },
  { name: "Caleb Shaw", avatar: "https://randomuser.me/api/portraits/men/94.jpg", registered: "2024-08-27", earned: 139500, rating: 4, comment: "Risk management tools help me control my exposure on each trade." },
  { name: "Nina Reyes", avatar: "https://randomuser.me/api/portraits/women/94.jpg", registered: "2024-08-13", earned: 110500, rating: 4, comment: "Support actually replies with useful answers instead of canned responses." },
  { name: "Diana Flores", avatar: "https://randomuser.me/api/portraits/women/95.jpg", registered: "2024-02-28", earned: 204500, rating: 5, comment: "Onboarding and KYC were straightforward, I was trading the same day." },
  { name: "Victor Kaur", avatar: "https://randomuser.me/api/portraits/men/95.jpg", registered: "2024-07-26", earned: 173000, rating: 4, comment: "Mobile layout is clean, I can monitor my open trades without stress." },
  { name: "Olivia Singh", avatar: "https://randomuser.me/api/portraits/women/96.jpg", registered: "2024-05-30", earned: 176500, rating: 4, comment: "The learning curve was gentle thanks to the in-app tutorials." },
  { name: "Warren Iqbal", avatar: "https://randomuser.me/api/portraits/men/96.jpg", registered: "2024-04-17", earned: 128500, rating: 4, comment: "Copy trading has been a nice way to diversify without watching charts all day." },
  { name: "Sophia Yamada", avatar: "https://randomuser.me/api/portraits/women/97.jpg", registered: "2024-03-04", earned: 298000, rating: 5, comment: "VIP tiers push me to stay disciplined and stick to my trading rules." },
  { name: "Xavi Tanaka", avatar: "https://randomuser.me/api/portraits/men/97.jpg", registered: "2024-01-07", earned: 217500, rating: 5, comment: "I appreciate how transparent the fees and commissions are." },
  { name: "Hannah Kato", avatar: "https://randomuser.me/api/portraits/women/98.jpg", registered: "2024-09-05", earned: 167500, rating: 4, comment: "Charts are responsive and the drawing tools feel smooth to use." },
  { name: "Yousef Franco", avatar: "https://randomuser.me/api/portraits/men/98.jpg", registered: "2024-02-09", earned: 192500, rating: 4, comment: "The dashboard makes it easy to see overall performance at a glance." },
  { name: "Zoe Torres", avatar: "https://randomuser.me/api/portraits/women/99.jpg", registered: "2024-06-24", earned: 121000, rating: 4, comment: "Email alerts and notifications are timed well, not spammy at all." },
  { name: "Ulrich Lopez", avatar: "https://randomuser.me/api/portraits/men/60.jpg", registered: "2024-05-11", earned: 209500, rating: 5, comment: "Everything feels stable — no random freezes when the market moves fast." }



];

export const overallRating = {
  rating: (() => {
    const total = reviewsData.reduce((sum, r) => sum + r.rating, 0);
    return Math.round((total / reviewsData.length) * 100) / 100;
  })(),
  votes: reviewsData.length,
  gradeDistribution: (() => {
    const counts = { 5: 0, 4: 0, 3: 0, 2: 0, 1: 0 };
    reviewsData.forEach(r => (counts[r.rating] = (counts[r.rating] || 0) + 1));
    const pct = {};
    Object.keys(counts).forEach(k => (pct[k] = Math.round((counts[k] / reviewsData.length) * 100)));
    return pct;
  })()
};
