import React, { useState, useEffect } from "react";
import api from "../utils/axiosInstance"; 
import "./AdminSignals.css";

const levels = ["trial", "bronze", "silver", "gold", "diamond", "platinum"];

export default function AdminSignals() {
  const [level, setLevel] = useState("");
  const [durationDays, setDurationDays] = useState("");
  const [expectedProfit, setExpectedProfit] = useState("");
  const [commissionRate, setCommissionRate] = useState("");
  const [signals, setSignals] = useState([]);

  // 📡 Fetch all signals
  const fetchSignals = async () => {
    try {
      const res = await api.get("/api/admin/signal-codes");
      setSignals(res.data.codes || res.data); // backend may return { codes }
    } catch (err) {
      console.error("Error fetching signals", err);
    }
  };

  useEffect(() => {
    fetchSignals();
  }, []);

  // ⚡ Generate new signal
  const generateSignal = async () => {
    if (!level || !durationDays || !expectedProfit || !commissionRate) {
      return alert("Please fill all fields");
    }

    try {
      await api.post("/api/admin/signal-codes", {
        level,
        durationDays: Number(durationDays),
        expectedProfit: expectedProfit.includes(",")
          ? expectedProfit.split(",").map(Number)
          : Number(expectedProfit),
        commissionRate: Number(commissionRate),
      });

      fetchSignals();
      setLevel("");
      setDurationDays("");
      setExpectedProfit("");
      setCommissionRate("");
    } catch (err) {
      console.error("Error creating signal", err);
      alert(err.response?.data?.message || "Failed to create signal");
    }
  };

  // 🔄 Toggle signal status
  const toggleSignal = async (id) => {
    try {
      await api.patch(`/api/admin/signal-codes/${id}/toggle`);
      fetchSignals();
    } catch (err) {
      console.error("Error toggling signal", err);
    }
  };

  // 🗑️ Delete signal
  const deleteSignal = async (id) => {
    if (!window.confirm("Delete this signal?")) return;
    try {
      await api.delete(`/api/admin/signal-codes/${id}`);
      fetchSignals();
    } catch (err) {
      console.error("Error deleting signal", err);
    }
  };

  return (
    <div className="admin-signals">
      <h2>📡 Admin Signal Codes</h2>

      {/* FORM */}
      <div className="signal-form">
        <select value={level} onChange={(e) => setLevel(e.target.value)}>
          <option value="">-- Select Level --</option>
          {levels.map((lvl) => (
            <option key={lvl} value={lvl}>
              {lvl}
            </option>
          ))}
        </select>

        <input
          type="number"
          placeholder="Duration (days)"
          value={durationDays}
          onChange={(e) => setDurationDays(e.target.value)}
        />

        <input
          type="text"
          placeholder="Expected Profit (e.g. 20 or 10,30)"
          value={expectedProfit}
          onChange={(e) => setExpectedProfit(e.target.value)}
        />

        <input
          type="number"
          placeholder="Commission Rate %"
          value={commissionRate}
          onChange={(e) => setCommissionRate(e.target.value)}
        />

        <button onClick={generateSignal}>Generate Signal</button>
      </div>

      {/* TABLE */}
      <h3>Generated Signals</h3>
      <table className="signal-table">
        <thead>
          <tr>
            <th>Code</th>
            <th>Level</th>
            <th>Duration</th>
            <th>Profit</th>
            <th>Commission</th>
            <th>Status</th>
            <th>Generated By</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {signals.length === 0 ? (
            <tr>
              <td colSpan="8">No signals yet.</td>
            </tr>
          ) : (
            signals.map((sig) => (
              <tr key={sig._id}>
                <td>{sig.code}</td>
                <td className={`level ${sig.level}`}>{sig.level}</td>
                <td>{sig.durationDays} days</td>
                <td>
                  {Array.isArray(sig.expectedProfit)
                    ? `${sig.expectedProfit[0]} - ${sig.expectedProfit[1]}%`
                    : `${sig.expectedProfit}%`}
                </td>
                <td>{sig.commissionRate}%</td>
                <td>{sig.isActive ? "✅ Active" : "❌ Inactive"}</td>
                <td>{sig.generatedBy?.email || "—"}</td>
                <td>
                  <button onClick={() => toggleSignal(sig._id)}>
                    {sig.isActive ? "Deactivate" : "Activate"}
                  </button>
                  <button
                    onClick={() => deleteSignal(sig._id)}
                    className="danger"
                  >
                    Delete
                  </button>
                </td>
              </tr>
            ))
          )}
        </tbody>
      </table>
    </div>
  );
}
